[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }
anyhow = "1.0.98"
readability = { version = "0.2.2", package = "readability-fork" }
url = "2.5.4"
openssl = { version = "0.10", features = ["vendored"] }
